-- 1. Safely drop tables ignoring foreign key constraints during teardown
DROP TABLE IF EXISTS customer CASCADE;
DROP TABLE IF EXISTS customer_tags CASCADE;
DROP TABLE IF EXISTS order_line CASCADE;
DROP TABLE IF EXISTS product CASCADE;
DROP TABLE IF EXISTS product_order CASCADE;

-- 2. Create tables with inline primary keys and standardized snake_case naming
CREATE TABLE customer (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          first_name VARCHAR(255),
                          last_name VARCHAR(255),
                          version INTEGER,
                          orders_id INTEGER
);

CREATE TABLE customer_tags (
                               customer_id BIGINT NOT NULL,
                               tags VARCHAR(255)
);

CREATE TABLE order_line (
                            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            amount INTEGER NOT NULL,
                            count INTEGER NOT NULL,
                            order_id INTEGER,
                            product_id INTEGER,
                            lines_id INTEGER
);

CREATE TABLE product (
                         id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         currency VARCHAR(255),
                         name VARCHAR(255),
                         price_in_cents INTEGER NOT NULL
);

CREATE TABLE product_order (
                               id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               notes VARCHAR(255),
                               customer_id BIGINT NOT NULL
);

-- 3. Add Constraints with human-readable names and explicit reference columns
ALTER TABLE product_order
    ADD CONSTRAINT uk_product_order_customer UNIQUE (customer_id);

ALTER TABLE customer
    ADD CONSTRAINT fk_customer_product_order FOREIGN KEY (orders_id) REFERENCES product_order(id);

ALTER TABLE customer_tags
    ADD CONSTRAINT fk_customer_tags_customer FOREIGN KEY (customer_id) REFERENCES customer(id);

ALTER TABLE order_line
    ADD CONSTRAINT fk_order_line_product_order FOREIGN KEY (order_id) REFERENCES product_order(id);

ALTER TABLE order_line
    ADD CONSTRAINT fk_order_line_product FOREIGN KEY (product_id) REFERENCES product(id);

ALTER TABLE order_line
    ADD CONSTRAINT fk_order_line_lines FOREIGN KEY (lines_id) REFERENCES product_order(id);

ALTER TABLE product_order
    ADD CONSTRAINT fk_product_order_customer FOREIGN KEY (customer_id) REFERENCES customer(id);

-- 4. Insert data (omitting the auto-generated ID column)
INSERT INTO customer (first_name, last_name, version)
VALUES ('Hugh', 'Jackman', 999);