drop table customer if exists;
drop table customer_tags if exists;
drop table OrderLine if exists;
drop table Product if exists;
drop table product_order if exists;
create table Customer (id bigint generated by default as identity, firstName varchar(255), lastName varchar(255), version integer, orders_id integer, primary key (id));
create table Customer_tags (Customer_id bigint not null, tags varchar(255));
create table OrderLine (id integer generated by default as identity, amount integer not null, count integer not null, order_id integer, product_id integer, lines_id integer, primary key (id));
create table Product (id integer generated by default as identity, currency varchar(255), name varchar(255), priceInCents integer not null, primary key (id));
create table product_order (id integer generated by default as identity, notes varchar(255), customer_id bigint not null, primary key (id));
alter table product_order add constraint UK_f1heq6dqsqx46ajqth9vb4nx2 unique (customer_id);
alter table Customer add constraint FK_5hhoeoudj31qtmcr8vldxifos foreign key (orders_id) references product_order;
alter table Customer_tags add constraint FK_5kbb0wdjp8ve3d76i1qrdu4x foreign key (Customer_id) references Customer;
alter table OrderLine add constraint FK_7f5oomg479mwt3dm02blnn6r2 foreign key (order_id) references product_order;
alter table OrderLine add constraint FK_5icddmxagb98vt3oqbxposife foreign key (product_id) references Product;
alter table OrderLine add constraint FK_bbixl908bc7i4pnf0oa1u5830 foreign key (lines_id) references product_order;
alter table product_order add constraint FK_f1heq6dqsqx46ajqth9vb4nx2 foreign key (customer_id) references Customer;

insert into customer (id, firstName, lastName, version) values (null, 'Hugh', 'Jackman', 999);
