language: java
jdk:
  - openjdk17

cache:
  directories:
    - "$HOME/.m2/repository"

script: mvn clean test -DtrimStackTrace=false -DuseFile=false

after_success:
  - mvn clean test jacoco:report coveralls:report
